greenery:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: corise
      password: corise
      port: 5432
      database: dbt
      schema: public
      threads: 4